// Class automatically generated by Dev-C++ New Class wizard

#ifndef SHORTCUTITEM_H
#define SHORTCUTITEM_H

#ifndef WX_PRECOMP
	#include <wx/wx.h>
	#include <wx/dialog.h>
#else
	#include <wx/wxprec.h>
#endif

#include <wx/log.h>

/*
 * No description
 */
WX_DECLARE_STRING_HASH_MAP( wxString, MyStringHash );

class ShortcutItem
{
 public:
    // class constructor
    ShortcutItem(int count, MyStringHash *SkillStrHash, MyStringHash *SkillNameHash, MyStringHash *ItemNameHash);
    // class destructor
    ~ShortcutItem();
    bool SetItem(int type, int id, int count, bool active);
    int GetItemID()
    {
        return ItemID;
    }
    
    void SetCount(int x)
    {
        Count = x;
    }
    int GetCount()
    {
        return Count;
    }
    
    int GetType()
    {
        return Type;
    }
    
    void SetName(wxString x)
    {
        Name = x;
    }
    wxString GetName()
    {
        return Name;
    }
    
    void SetActiveFlag(bool x)
    {
        isActive = x;
    }
    bool GetActiveFlag()
    {
        return isActive;
    }
    
    // No description
    bool Draw(wxPaintDC *dc);
    
    
 private:
    MyStringHash *SkillId2Str;
    MyStringHash *SkillId2Name;
    MyStringHash *ItemId2Name;
    // Skill or Item ID
    int ItemID;
    /**
     * Skill Level or Item Count
     * If Type is Skill and Count is 0.
     * Skill is not Level Selectable
     */
    int Count;
    /**
     * Item Type
     * 0 = NULL
     * 1 = Skill
     * 2 = Item
     */
    int Type;
    wxString Name;
    /**
     * Active Flag
     * true  : active
     * false : non active
     */
    bool isActive;
    wxBitmap *KeyImage;
    // No description
    int PositionCount;
    // No description
    bool DrawFlag;
    // No description
    wxBitmap *ItemImage;
};

#endif // SHORTCUTITEM_H
